- name: Install microsoft auto-update
  homebrew_cask:
    name: microsoft-auto-update
    state: present
  tags:
    - apps
    - office
- name: Install Microsoft Word
  homebrew_cask:
    name: microsoft-word
    state: present
  tags:
    - apps
    - office
    - word
- name: Install Microsoft Excel
  homebrew_cask:
    name: microsoft-excel
    state: present
  tags:
    - apps
    - office
    - excel
- name: Install Microsoft Powerpoint
  homebrew_cask:
    name: microsoft-powerpoint
    state: present
  tags:
    - apps
    - office
    - powerpoint

- name: Install Microsoft Teams
  homebrew_cask:
    name: microsoft-teams
    state: present
  tags:
    - apps
    - meetings
    - teams
- name: Install Slack
  homebrew_cask:
    name: slack
    state: present
  tags:
    - apps
    - meetings
    - slack
- name: Install Zoom
  homebrew_cask:
    name: zoom
    state: present
  tags:
    - apps
    - meetings
    - zoom
- name: Install Webex
  homebrew_cask:
    name: webex
    state: present
  tags:
    - apps
    - meetings
    - webex
- name: Install Skype
  homebrew_cask:
    name: skype
    state: present
  tags:
    - apps
    - meetings
    - skype

- name: Install Firefox
  homebrew_cask:
    name: firefox
    state: present
  tags:
    - apps
    - browsers
    - firefox
- name: Install Chrome
  homebrew_cask:
    name: google-chrome
    state: present
  tags:
    - apps
    - browsers
    - chrome

- name: Install Tripmode
  homebrew_cask:
    name: tripmode
    state: present
  tags:
    - apps
    - utilities
    - tripmode
- name: Install Magnet
  mas:
    id: 441258766
    state: present
  tags:
    - apps
    - utilities
    - magnet
- name: Install NeoVim
  homebrew:
    name: neovim
    state: present
  tags:
    - apps
    - utilities
    - nvim
- name: Install Vim-Plug
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - apps
    - utilities
    - dotfiles
    - nvim
- name: Install Tmux
  homebrew:
    name: tmux
    state: present
  tags:
    - apps
    - utilities
    - tmux

- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code
    state: present
  tags:
    - apps
    - development
    - vscode

- name: Install Kindle
  homebrew_cask:
    name: kindle
    state: present
  tags:
    - apps
    - kindle

- name: Install NordVPN
  homebrew_cask:
    name: nordvpn
    state: present
  tags:
    - apps
    - nordvpn

- name: Install VLC
  homebrew_cask:
    name: vlc
    state: present
  tags:
    - apps
    - vlc